services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:8888
    depends_on:
      - backend

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "8888:8888"
    environment:
      - PORT=8888
      - SIMULATION_API_URL=http://simulation:5555
      - ENV=development
    command: go run main.go
    depends_on:
      - simulation

  # Simulation service
  simulation:
    build:
      context: ./simulation
      dockerfile: Dockerfile.dev
    volumes:
      - ./simulation:/app
    ports:
      - "5555:5555"
    environment:
      - PORT=5555
      - PYTHONPATH=/app
    command: python -m src.quantum_simulator.main
