name: Simulation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'quantum-circuit-editor/simulation/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: quantum-circuit-editor/simulation

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for pre-commit file history checks

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install pre-commit

    - name: Run pre-commit
      run: pre-commit run --all-files --show-diff-on-failure

    - name: Run tests
      run: pytest --cov=src tests/

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./quantum-circuit-editor/simulation/coverage.xml
        fail_ci_if_error: false
